name: Generate font subset (I.Ming)

on:
  schedule:
    - cron: "18 18 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fonttools brotli

      - name: Get font source
        run: |
          wget https://github.com/ichitenfont/I.Ming/raw/master/8.00/I.Ming-8.00.ttf

      - name: Generate font subset
        run: |
          python extract_font.py

      - name: Remove font source
        run: |
          rm I.Ming-8.00.ttf

      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "Generate font subset (I.Ming)"
